export const assets = {
  airplayIcon: require('./airplay.png'),
  appStoreIcon: require('./app-store.png'),
  appleLogo: require('./apple-logo.png'),
  batteryIcon: require('./battery.png'),
  binIcon: require('./bin.png'),
  folderIcon: require('./folder.png'),
  newsIcon: require('./news.png'),
  notesIcon: require('./notes.png'),
  safariIcon: require('./safari-icon.png'),
  searchIcon: require('./search.png'),
  messageIcon: require('./messages.png'),
  pdfIcon: require('./pdf-image.png'),
  cv: require('./Harvind_Sokhal_CV.pdf'),
}

export const notesAssets = {
  smallSectionIcons: require('./notes-small-sec-icons.png'),
  largeSectionIcons: require('./notes-large-section-icons.png'),
  typescriptIcon: require('./typescript.png'),
  htmlIcon: require('./htmlIcon.png'),
  cssIcon: require('./cssIcon.webp'),
  kotlinIcon: require('./kotlin-icon.png'),
  pythonIcon: require('./pythonIcon.png'),
  scalaIcon: require('./scalaIcon.png'),
  javaIcon: require('./javaIcon.jpg'),
  reactIcon: require('./reactIcon.png'),
  expressIcon: require('./expressIcon.png'),
  nestIcon: require('./nestIcon.png'),
  graphqlIcon: require('./graphqlIcon.png'),
  springIcon: require('./springIcon.png'),
  jiraIcon: require('./jiraIcon.svg').default,
  prettierIcon: require('./prettierIcon.svg').default,
  eslintIcon: require('./eslintIcon.png'),
  gitIcon: require('./gitIcon.png'),
  dockerIcon: require('./dockerIcon.png'),
  kubernetesIcon: require('./kubernetesIcon.png'),
  circleciIcon: require('./circleciIcon.png'),
  storybookIcon: require('./storybookIcon.png'),
  jestIcon: require('./jestIcon-min.png'),
  datadogIcon: require('./datadogIcon.png'),
}

export const appStoreAssets = {
  discoverIcon: require('./Discover-store.png'),
  createIcon: require('./Create-store.png'),
  workIcon: require('./Work-store.png'),
  playIcon: require('./Play-store.png'),
  developIcon: require('./Develop-store.png'),
  categoriesIcon: require('./Catagories-store.png'),
  updateIcon: require('./Updates-store.png'),
  profileIcon: require('./profile-store.png'),
  highlight1: require('./highlight1.png'),
  highlight2: require('./highlight2.jpeg'),
  flappyBirdIcon: require('./flappy-bird.png'),
  oculusIcon: require('./oculus.jpg'),
  pokemonIcon: require('./pokemon.jpeg'),
  scrapperIcon: require('./scrapper.png'),
  musicIcon: require('./music.png'),
  snakeIcon: require('./snake.png'),
}

export const safariAssets = {
  sidebarIcon: require('./sidebar.png'),
  backarrowIcon: require('./backarrow.png'),
  frontarrowIcon: require('./frontarrow.png'),
  shieldIcon: require('./shield.png'),
  lockIcon: require('./lock.png'),
  refreshIcon: require('./refresh.png'),
  cloudIcon: require('./cloud.png'),
  shareIcon: require('./share.png'),
  plusIcon: require('./plus.png'),
  tabsIcon: require('./tabs.png'),
  xIcon: require('./x-icon.png'),
  linkedinIcon: require('./linkedin-icon.png'),
  threadsIcon: require('./threads-icon.png'),
  xScreenshot: require('./x-screenshot.png'),
  linkedinScreenshot: require('./linkedin-screenshot.png'),
  threadsScreenshot: require('./threads-screenshot.png'),
}

export const messageAssets = {
  editIcon: require('./edit-button.png'),
  sendIcon: require('./send.png'),
  addIcon: require('./add.png'),
}
